import random

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import StreamingResponse
from loguru import logger

from app.sites.generator import generate_web_page
from app.sites.schemas import CreateSiteRequest, GeneratedSitesResponse, SiteGenerationRequest, SiteResponse
from storage import create_site_record, get_all_sites, update_site_title

router = APIRouter(
    prefix="/sites",
    tags=["Sites"]
)


@router.post(
    "/create",
    summary="Create a new website from a user prompt",
    response_description="Generated website data",
    response_model=SiteResponse
)
async def create_site(payload: CreateSiteRequest, request: Request):
    settings = request.app.state.settings
    database = request.app.state.database
    s3_client = request.app.state.s3_client

    site_id = random.randint(1, 1000000)
    title = payload.title or "Generated Website"

    new_site = await create_site_record(
        s3_settings=settings.S3,
        s3_client=s3_client,
        site_id=site_id,
        title=title,
        prompt=payload.prompt,
        database=database
    )
    return new_site


@router.post(
    "/{site_id}/generate",
    summary="Generate a website with AI stream",
    response_description="Chunks of HTML code from the generated website",
)
async def generate_site(site_id: int, payload: SiteGenerationRequest, request: Request):
    settings = request.app.state.settings
    database = request.app.state.database

    site = database.get(site_id)
    if not site:
        logger.warning(f"Generation rejected: site {site_id} not found")
        raise HTTPException(status_code=404, detail="Site not found")

    async def handle_title(generated_title: str):
        update_site_title(database=database, site_id=site_id, title=generated_title)

    return StreamingResponse(
        generate_web_page(
            site_id=site_id,
            user_prompt=payload.prompt,
            debug_mode=settings.DEBUG,
            request=request,
            on_title_found=handle_title
        ),
        media_type="text/plain; charset=utf-8"
    )


@router.get(
    "/my",
    summary="Get all websites generated by the current user",
    response_description="User-generated websites",
    response_model=GeneratedSitesResponse
)
async def get_user_sites(request: Request):
    database = request.app.state.database
    sites = get_all_sites(database=database)
    return {"sites": sites}


@router.get(
    "/{site_id}",
    summary="Get details of a specific generated website",
    response_description="HTML code of the generated website",
    response_model=SiteResponse
)
async def get_site_by_id(site_id: int, request: Request):
    database = request.app.state.database

    site = database.get(site_id)
    if not site:
        logger.warning(f"Fetch failed: site {site_id} not found")
        raise HTTPException(status_code=404, detail="Site not found")
    return site
