import random

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import StreamingResponse
from loguru import logger

from app.sites.generator import generate_web_page
from app.sites.schemas import CreateSiteRequest, GeneratedSitesResponse, SiteGenerationRequest, SiteResponse
from app.sites.services import create_site_record, get_all_sites

router = APIRouter(
    prefix="/sites",
    tags=["Sites"]
)


@router.post(
    "/create",
    summary="Create a new website from a user prompt",
    response_description="Generated website data",
    response_model=SiteResponse
)
async def create_site(payload: CreateSiteRequest, request: Request):
    db = request.app.state.database

    site_id = random.randint(1, 1000000)
    title = payload.title or "Generated Website"

    new_site = await create_site_record(
        db=db,
        site_id=site_id,
        title=title,
        prompt=payload.prompt
    )
    return new_site


@router.post(
    "/{site_id}/generate",
    summary="Generate a website with AI stream",
    response_description="Chunks of HTML code from the generated website",
)
async def generate_site(payload: SiteGenerationRequest, request: Request, site_id: int):
    settings = request.app.state.settings
    s3_client = request.app.state.s3_client
    gotenberg_client = request.app.state.gotenberg_client
    db = request.app.state.database

    site = db.get(site_id)
    if not site:
        logger.warning(f"Generation rejected: site_{site_id} not found")
        raise HTTPException(status_code=404, detail="Site not found")

    return StreamingResponse(
        generate_web_page(
            db=db,
            s3_client=s3_client,
            gotenberg_client=gotenberg_client,
            settings=settings,
            request=request,
            site_id=site_id,
            user_prompt=payload.prompt
        ),
        media_type="text/plain; charset=utf-8"
    )


@router.get(
    "/my",
    summary="Get all websites generated by the current user",
    response_description="User-generated websites",
    response_model=GeneratedSitesResponse
)
async def get_user_sites(request: Request):
    db = request.app.state.database
    sites = get_all_sites(db=db)
    return {"sites": sites}


@router.get(
    "/{site_id}",
    summary="Get details of a specific generated website",
    response_description="HTML code of the generated website",
    response_model=SiteResponse
)
async def get_site_by_id(request: Request, site_id: int):
    db = request.app.state.database

    site = db.get(site_id)
    if not site:
        logger.warning(f"Fetch failed: site_{site_id} not found")
        raise HTTPException(status_code=404, detail="Site not found")
    return site
