from datetime import datetime
from urllib.parse import urlencode, urljoin

import httpx
from aiobotocore.client import AioBaseClient
from loguru import logger

from app.sites.screenshot import generate_screenshot
from core.env_settings import AppSettings, S3Settings
from storage import save_screenshot_to_s3


async def create_site_record(db: dict, site_id: int, title: str, prompt: str) -> dict:
    """Creates a record in the database."""
    new_site = {
        "id": site_id,
        "title": title,
        "prompt": prompt,
        "html_code_url": None,
        "html_code_download_url": None,
        "screenshot_url": None,
        "created_at": datetime.now(),
        "updated_at": datetime.now()
    }
    db[site_id] = new_site
    logger.info(f"Database record created for site_{site_id}")
    return new_site


def get_all_sites(db: dict) -> list[dict]:
    """Returns a list of all websites generated by the user."""
    return list(db.values())


async def process_screenshot(
    gotenberg_client: httpx.AsyncClient,
    s3_client: AioBaseClient,
    settings: AppSettings,
    site_id: int,
    html_code: str
) -> str:
    """Generates a screenshot via Gotenberg API and saves it to a bucket."""
    screenshot_bytes = await generate_screenshot(
        gotenberg_client=gotenberg_client,
        gotenberg_settings=settings.GOTENBERG,
        site_id=site_id,
        html_code=html_code
    )
    screenshot_key = await save_screenshot_to_s3(
        s3_client=s3_client,
        bucket_name=settings.S3.BUCKET_NAME,
        site_id=site_id,
        screenshot_bytes=screenshot_bytes,
        screenshot_format=settings.GOTENBERG.SCREENSHOT_FORMAT
    )
    return screenshot_key


def update_site_artifacts(
    db: dict,
    s3_settings: S3Settings,
    site_id: int,
    site_title: str,
    site_key: str,
    screenshot_key: str
) -> None:
    """Updates the site artifacts in the database."""
    base_url = s3_settings.BASE_URL
    html_file_path = f"{s3_settings.BUCKET_NAME}/{site_key}"
    html_file_url = urljoin(base_url, html_file_path)

    preview_params = urlencode({
        "content-type": "text/html",
        "content-disposition": "inline"
    })
    download_params = urlencode({
        "response-content-disposition": 'attachment; filename="index.html"'
    })

    html_code_url = f"{html_file_url}?{preview_params}"
    html_code_download_url = f"{html_file_url}?{download_params}"

    screenshot_path = f"{s3_settings.BUCKET_NAME}/{screenshot_key}"
    screenshot_url = urljoin(base_url, screenshot_path)

    site = db.get(site_id)

    site.update({
        "title": site_title,
        "html_code_url": html_code_url,
        "html_code_download_url": html_code_download_url,
        "screenshot_url": screenshot_url,
        "updated_at": datetime.now()
    })
