import asyncio
from collections.abc import AsyncGenerator
from pathlib import Path

from fastapi import FastAPI
from fastapi.responses import StreamingResponse
from fastapi.staticfiles import StaticFiles

from api_models import (
    CreateSiteRequest,
    GeneratedSitesResponse,
    SiteGenerationRequest,
    SiteResponse,
    UserDetailsResponse,
)
from config import FRONTEND_DIR

MOCK_HTML_FILE = Path("mock_site.html").absolute()
MOCK_SITE_DATA = {
    "id": 1,
    "title": "My Site",
    "html_code_url": "https://dvmn.org/media/filer_public/d1/4b/d14bb4e8-d8b4-49cb-928d-fd04ecae46da/index.html",
    "html_code_download_url": "https://dvmn.org/media/filer_public/d1/4b/d14bb4e8-d8b4-49cb-928d-fd04ecae46da/index.html?response-content-disposition=attachment",
    "screenshot_url": None,
    "prompt": "Create a website.",
    "created_at": "2026-09-15T18:29:56+00:00",
    "updated_at": "2026-09-15T19:00:00+00:00"
}


async def fake_ai_generation_stream(file_path: Path, chunk_size: int = 512) -> AsyncGenerator:
    """Reads the HTML file step-by-step and serves it in chunks."""
    if not file_path.exists():
        yield f"error: File '{file_path.name}' was not found on the disk."
        return

    with open(file_path, "r", encoding="utf-8") as file:
        while True:
            chunk = file.read(chunk_size)
            if not chunk:
                break

            yield chunk

            await asyncio.sleep(1)


app = FastAPI(title="AI Website Generator", description="AI-powered website generator built with FastAPI")


@app.get(
    "/users/me",
    tags=["Users"],
    summary="Retrieve user credentials",
    response_description="User credentials",
    response_model=UserDetailsResponse,
)
def get_user():
    mock_user_data = {
        "profileId": 1,
        "username": "user123",
        "email": "example@example.com",
        "isActive": True,
        "registeredAt": "2025-06-15T18:29:56+00:00",
        "updatedAt": "2026-09-15T18:29:56+00:00",
    }
    return mock_user_data


@app.post(
    "/sites/create",
    tags=["Sites"],
    summary="Create a new website from a user prompt",
    response_description="Generated website",
    response_model=SiteResponse
)
def create_site(payload: CreateSiteRequest):
    new_site = MOCK_SITE_DATA.copy()
    if payload.title:
        new_site["title"] = payload.title
    new_site["prompt"] = payload.prompt
    return new_site


@app.post(
    "/sites/{site_id}/generate",
    tags=["Sites"],
    summary="Generate a website with AI stream",
    response_description="Chunks of HTML code from the generated website",
)
async def generate_site(site_id: int, payload: SiteGenerationRequest):
    return StreamingResponse(
        fake_ai_generation_stream(file_path=MOCK_HTML_FILE, chunk_size=512),
        media_type="text/plain; charset=utf-8"
    )


@app.get(
    "/sites/my",
    tags=["Sites"],
    summary="Get all websites generated by the current user",
    response_description="User-generated websites",
    response_model=GeneratedSitesResponse
)
async def get_user_sites():
    return {
        "sites": [MOCK_SITE_DATA]
    }


@app.get(
    "/sites/{site_id}",
    tags=["Sites"],
    summary="Get details of a specific generated website",
    response_description="HTML code of the generated website",
    response_model=SiteResponse
)
async def get_site_by_id(site_id: int):
    site_data = MOCK_SITE_DATA.copy()
    site_data["site_id"] = site_id
    return site_data


app.mount("/assets", StaticFiles(directory=f"{FRONTEND_DIR}/assets"), name="assets")
app.mount("/", StaticFiles(directory=FRONTEND_DIR, html=True), name="frontend")
