from datetime import datetime
from typing import Any
from urllib.parse import urlencode, urljoin

from aiobotocore.client import AioBaseClient
from botocore.exceptions import ClientError

from env_settings import S3Settings


async def ensure_bucket_exists(s3_client: AioBaseClient, bucket_name: str) -> None:
    """Checks for the existence of a bucket at startup."""
    try:
        await s3_client.head_bucket(Bucket=bucket_name)
    except ClientError:
        raise RuntimeError(f"An error occurred: Bucket '{bucket_name}' not found")


async def save_html_to_s3(
    s3_client: AioBaseClient,
    bucket_name: str,
    site_id: int,
    html_code: str
) -> None:
    """Uploads a file with the `text/html` type to a bucket."""
    await s3_client.put_object(
        Bucket=bucket_name,
        Key=f"site_{site_id}.html",
        Body=html_code.encode("utf-8"),
        ContentType="text/html",
        ContentEncoding="utf-8"
    )


async def create_site_record(
    s3_settings: S3Settings,
    site_id: int,
    title: str,
    prompt: str,
    database: dict
) -> dict[str, Any]:
    """Creates a record in the database."""
    base_url = s3_settings.BASE_URL
    file_path = f"{s3_settings.BUCKET_NAME}/site_{site_id}.html"
    full_file_url = urljoin(base_url, file_path)

    preview_params = urlencode({
        "content-type": "text/html",
        "content-disposition": "inline"
    })
    download_params = urlencode({
        "response-content-disposition": 'attachment; filename="index.html"'
    })

    html_code_url = f"{full_file_url}?{preview_params}"
    html_code_download_url = f"{full_file_url}?{download_params}"

    new_site = {
        "id": site_id,
        "title": title,
        "prompt": prompt,
        "html_code_url": html_code_url,
        "html_code_download_url": html_code_download_url,
        "screenshot_url": None,
        "created_at": datetime.now(),
        "updated_at": datetime.now()
    }
    database[site_id] = new_site
    return new_site


def get_all_sites(database: dict) -> list[dict[str, Any]]:
    """Returns a list of all sites generated by the user."""
    return list(database.values())


def update_site_title(database: dict, site_id: int, title: str) -> None:
    """Updates the title of a site."""
    site = database.get(site_id)
    if site:
        database[site_id]["title"] = title
        database[site_id]["updated_at"] = datetime.now()
