from datetime import datetime
from typing import Any
from urllib.parse import urlencode, urljoin

from aiobotocore.client import AioBaseClient
from botocore.exceptions import ClientError
from loguru import logger

from env_settings import S3Settings


async def ensure_bucket_exists(s3_client: AioBaseClient, bucket_name: str) -> None:
    """Checks for the existence of a bucket at startup."""
    try:
        await s3_client.head_bucket(Bucket=bucket_name)
    except ClientError:
        logger.critical(f"Bucket {bucket_name} not found")
        raise RuntimeError(f"Bucket {bucket_name} not found")


async def save_html_to_s3(
    s3_client: AioBaseClient,
    bucket_name: str,
    site_id: int,
    html_code: str
) -> None:
    """Uploads a file with the `text/html` type to a bucket."""
    site_key = f"site_{site_id}.html"
    try:
        await s3_client.put_object(
            Bucket=bucket_name,
            Key=site_key,
            Body=html_code.encode("utf-8"),
            ContentType="text/html",
            ContentEncoding="utf-8"
        )
        logger.success(f"{site_key} has been successfully saved to {bucket_name} bucket")
    except ClientError as e:
        logger.error(f"Failed to put {site_key} into {bucket_name} bucket: {e}")
        return
    except Exception as e:
        logger.exception(f"Unexpected error saving HTML to S3: {e}")
        return


async def save_screenshot_to_s3(
    s3_client: AioBaseClient,
    bucket_name: str,
    site_id: int,
    screenshot_bytes: bytes,
    screenshot_format: str
) -> None:
    """Uploads a screenshot file to a bucket."""
    screenshot_key = f"screenshot_{site_id}.{screenshot_format}"
    try:
        await s3_client.put_object(
            Bucket=bucket_name,
            Key=screenshot_key,
            Body=screenshot_bytes,
            ContentType=f"image/{screenshot_format}"
        )
        logger.success(f"{screenshot_key} successfully saved to {bucket_name} bucket")
    except ClientError as e:
        logger.error(f"Failed to put {screenshot_key} into {bucket_name} bucket: {e}")
        return
    except Exception as e:
        logger.exception(f"Unexpected error saving Screenshot to S3: {e}")
        return


async def create_site_record(
    s3_settings: S3Settings,
    s3_client: AioBaseClient,
    site_id: int,
    title: str,
    prompt: str,
    database: dict
) -> dict[str, Any]:
    """Creates a record in the database."""
    base_url = s3_settings.BASE_URL
    file_path = f"{s3_settings.BUCKET_NAME}/site_{site_id}.html"
    full_file_url = urljoin(base_url, file_path)

    preview_params = urlencode({
        "content-type": "text/html",
        "content-disposition": "inline"
    })
    download_params = urlencode({
        "response-content-disposition": 'attachment; filename="index.html"'
    })

    html_code_url = f"{full_file_url}?{preview_params}"
    html_code_download_url = f"{full_file_url}?{download_params}"

    new_site = {
        "id": site_id,
        "title": title,
        "prompt": prompt,
        "html_code_url": html_code_url,
        "html_code_download_url": html_code_download_url,
        "screenshot_url": None,
        "created_at": datetime.now(),
        "updated_at": datetime.now()
    }

    placeholder_html = """
    <!DOCTYPE html>
    <html lang="en">
    <html>
        <head>
            <meta charset='utf-8'>
            <style>
                body {
                    font-family: sans-serif;
                    text-align: center;
                    padding: 50px;
                    color: #555;
                }
            </style>
        </head>
        <body>
            <h2>Generation Error</h2>
            <p>If you are seeing this page, an error occurred during the site generation process.</p>
            <p>Try refreshing the page or regenerating the site.</p>
        </body>
    </html>
    """
    try:
        await s3_client.put_object(
            Bucket=s3_settings.BUCKET_NAME,
            Key=f"site_{site_id}.html",
            Body=placeholder_html.encode("utf-8"),
            ContentType="text/html"
        )
    except Exception as e:
        logger.error(f"Failed to create a placeholder for site {site_id}: {e}")

    database[site_id] = new_site
    logger.info(f"Database record created for site {site_id}")
    return new_site


def get_all_sites(database: dict) -> list[dict[str, Any]]:
    """Returns a list of all sites generated by the user."""
    return list(database.values())


def update_site_title(database: dict, site_id: int, title: str) -> None:
    """Updates the title of a site."""
    site = database.get(site_id)
    if site:
        database[site_id]["title"] = title
        database[site_id]["updated_at"] = datetime.now()
        logger.info(f"Title updated for site {site_id} to {title}")
